### ISSUE TITLE
ModuleNotFoundError: No module named 'caption.models.selfcritic'

### ISSUE THREAD

**Issue by pzhren** [cshizhe/asg2cap#10]

**Comment by cshizhe** [comment]
You could simply delete the line. It doesn't matter because I do not use self critical reinforcement training in this version of codes.

**Comment by pzhren** [comment]
Thank you very much for your reply.
I want to know if we need ./annotation/regionfiles when testing. 
In addition, how regionfiles/image_id.json is generated.
 In addition, when extracting region features, which one of them should be used image_bbox_extraction.py/image_feature_extraction_given_bbox.py, https://github.com/cshizhe/maskrcnn_benchmark

**Comment by pzhren** [comment]
More specifically, I want to pre-train on the visualGenome data set, and then generate captions for the new data set. I want to know that besides ordered_feature/MP and ordered_feature/SA, do I need regionfiles? If needed, how do I generate regionfiles for the new dataset. Thank you.
