### ISSUE TITLE
How do you generate scene graph of mscoco?

### ISSUE THREAD

**Issue by Einstone-rose** [cshizhe/asg2cap#6]
please give some details about how to generate sg of mscoco,thanks！

**Comment by cshizhe** [comment]
The details are in the [supplementary](https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Chen_Say_As_You_CVPR_2020_supplemental.pdf).

We use the [SPICE toolkit](https://github.com/peteanderson80/SPICE) to generate scene graphs from captions.
