### ISSUE TITLE
For a new image, how do I get its annotated JSON file

### ISSUE THREAD

**Issue by jxylon** [cshizhe/asg2cap#9]

**Comment by fuyun1107** [comment]
> _No description provided._

问题解决了吗？xd

**Comment by jxylon** [comment]
> > _No description provided._
> 
> 问题解决了吗？xd

没呢 -(

**Comment by cshizhe** [comment]
I am not sure about the meaning of your question. 
For a new image in the testing phase, the ASG is generated by users as described in Section 3 of our paper.
The format of the ASG should be organized in the same way as the [format in the training phase](https://github.com/cshizhe/asg2cap#annotations).
